"""A collection of classes used in the 'machine code' generated by Auto Maple's compiler for each routine."""

from src.common import config, settings, utils
import csv
import random
from os.path import splitext, basename
from src.routine.components import Point, Label, Jump, Setting, Command, SYMBOLS
from src.routine.layout import Layout
from src.common.logger import get_logger

log = get_logger(__name__)


def update(func):
    """
    Decorator function that updates both the displayed routine and details
    for all mutative Routine operations.
    """

    def f(self, *args, **kwargs):
        result = func(self, *args, **kwargs)
        config.gui.set_routine(self.display)
        config.gui.view.details.update_details()
        return result
    return f


def dirty(func):
    """Decorator function that sets the dirty bit for mutative Routine operations."""

    def f(self, *args, **kwargs):
        result = func(self, *args, **kwargs)
        self.dirty = True
        return result
    return f


class Routine:
    """Describes a routine file in Auto Maple's custom 'machine code'."""

    def __init__(self):
        self.dirty = False
        self.path = ''
        self.labels = {}
        self.index = 0
        self.sequence = []
        self.display = []       # Updated alongside sequence
        # Point Selection Randomization
        self.skip_probability = 0.30  # 30% chance to skip (tuned for better balance)
        self.consecutive_skips = 0
        self.max_consecutive_skips = random.randint(1, 3)  # Max 1-3 consecutive skips (hardcode random)
        self.skip_enabled = False  # Enable/disable skip feature - Can be enabled from GUI
        self.is_skipping_context = False  # Track if we're in skip context (for teleport decision)
        # Routine Pattern Variation
        self.variant_enabled = True
        self.current_variant = 'normal'
        self.variant_switch_counter = 0
        self.variant_switch_interval = random.randint(3, 7)  # Switch every 3-7 loops
        self.variant_cycle = []
        self.variant_cycle_index = 0
        self.floor_variant_active = False
        self.floor_variant_chance = 1.0  # 100% chance to activate floor-only variant after completing a loop (for testing)
        self.floor_variant_loop_range = (3, 5)  # Floor-only variants run for 3-5 loops, then return to normal
        self.floor_variant_last = None
        self.floor_direction = 'forward'  # Track direction in floor-only: 'forward' or 'reverse'
        self.floor1_indices = []  # Indices of Floor 1 points
        self.floor2_indices = []  # Indices of Floor 2 points
        self.loop_count = 0
        self.last_index = -1
        self.last_floor_index = -1  # Track last index within the same floor (for reverse teleport detection)
        
        # Load randomization settings from GUI
        self._load_randomization_settings()

    def _load_randomization_settings(self):
        """Load randomization settings from GUI settings file."""
        try:
            from src.gui.settings.routine_randomization import RoutineRandomizationSettings
            settings = RoutineRandomizationSettings('routine_randomization')
            
            # Load Point Selection settings
            self.skip_enabled = settings.get('Point Selection Enabled')
            self.skip_probability = settings.get('Point Selection Skip Probability')
            
            # Load Routine Pattern settings
            self.variant_enabled = settings.get('Routine Pattern Enabled')
            self.floor_variant_chance = settings.get('Routine Pattern Floor Only Chance')
        except Exception as e:
            # Settings might not be available yet, use defaults
            log.debug("Could not load randomization settings: %s", e)

    @dirty
    @update
    def set(self, arr):
        self.sequence = arr
        self.display = [str(x) for x in arr]

    @dirty
    @update
    def append_component(self, p):
        self.sequence.append(p)
        self.display.append(str(p))

    @dirty
    @update
    def append_command(self, i, c):
        """Appends Command object C to the Point at index I in the sequence."""

        target = self.sequence[i]
        target.commands.append(c)

    @dirty
    @update
    def move_component_up(self, i):
        """Moves the component at index I upward if possible."""

        if i > 0:
            temp_s = self.sequence[i-1]
            temp_d = self.display[i-1]
            self.sequence[i-1] = self.sequence[i]
            self.display[i-1] = self.display[i]
            self.sequence[i] = temp_s
            self.display[i] = temp_d
            return i - 1
        return i

    @dirty
    @update
    def move_component_down(self, i):
        if i < len(self.sequence) - 1:
            temp_s = self.sequence[i+1]
            temp_d = self.display[i+1]
            self.sequence[i+1] = self.sequence[i]
            self.display[i+1] = self.display[i]
            self.sequence[i] = temp_s
            self.display[i] = temp_d
            return i + 1
        return i

    @dirty
    @update
    def move_command_up(self, i, j):
        """
        Within the Point at routine index I, moves the Command at index J upward
        if possible and updates the Edit UI.
        """

        point = self.sequence[i]
        if j > 0:
            temp = point.commands[j-1]
            point.commands[j-1] = point.commands[j]
            point.commands[j] = temp
            return j - 1
        return j

    @dirty
    @update
    def move_command_down(self, i, j):
        point = self.sequence[i]
        if j < len(point.commands) - 1:
            temp = point.commands[j+1]
            point.commands[j+1] = point.commands[j]
            point.commands[j] = temp
            return j + 1
        return j

    @dirty
    @update
    def delete_component(self, i):
        """Deletes the Component at index I."""

        self.sequence.pop(i)
        self.display.pop(i)

    @dirty
    @update
    def delete_command(self, i, j):
        """Within the Point at routine index I, deletes the Command at index J."""

        point = self.sequence[i]
        point.commands.pop(j)

    @update
    def update_component(self, i, new_kwargs):
        target = self.sequence[i]
        try:
            target.update(**new_kwargs)
            self.display[i] = str(target)
            self.dirty = True
        except (ValueError, TypeError) as e:
            print(f"\n[!] Found invalid arguments for '{target.__class__.__name__}':")
            print(f"{' ' * 4} -  {e}")

    @update
    def update_command(self, i, j, new_kwargs):
        target = self.sequence[i].commands[j]
        try:
            target.update(**new_kwargs)
            self.display[i] = str(self.sequence[i])
            self.dirty = True
        except (ValueError, TypeError) as e:
            print(f"\n[!] Found invalid arguments for '{target.__class__.__name__}':")
            print(f"{' ' * 4} -  {e}")

    def should_skip_current_point(self):
        """
        Check if we should skip current point.
        Only skip Point components, never skip Jump, Label, Setting.
        Returns: True if should skip, False otherwise
        """
        if not self.skip_enabled:
            log.debug("Point Selection Randomization: DISABLED - Skip check for index %d", self.index)
            return False
        
        if len(self.sequence) == 0:
            log.debug("Point Selection Randomization: Empty sequence - Skip check for index %d", self.index)
            return False
        
        if self.index >= len(self.sequence):
            log.debug("Point Selection Randomization: Index out of range (%d >= %d)", self.index, len(self.sequence))
            return False
        
        element = self.sequence[self.index]
        element_type = element.__class__.__name__
        
        # NEVER skip non-Point components (Jump, Label, Setting, Comment)
        if not isinstance(element, Point):
            log.info("🔄 Point Selection Randomization: Index %d - %s (NOT a Point - will execute)", 
                    self.index, element_type)
            return False
        
        # Get point info for logging
        point_location = element.location if hasattr(element, 'location') else 'unknown'
        
        # Check consecutive skips - don't skip if we've skipped too many consecutive points
        if self.consecutive_skips >= self.max_consecutive_skips:
            log.info("✅ Point Selection Randomization: Index %d - Point %s - EXECUTE (max consecutive skips reached: %d/%d)", 
                    self.index, point_location, self.consecutive_skips, self.max_consecutive_skips)
            self.consecutive_skips = 0  # Reset after max reached
            # Regenerate max_consecutive_skips for next time (random 1-3)
            self.max_consecutive_skips = random.randint(1, 3)
            log.debug("🎲 Point Selection Randomization: New max consecutive skips set to %d", self.max_consecutive_skips)
            return False
        
        # Random skip probability
        random_value = random.random()
        should_skip = random_value < self.skip_probability
        
        if should_skip:
            self.consecutive_skips += 1
            log.info("⏭️ Point Selection Randomization: Index %d - Point %s - SKIP (probability: %.1f%%, random: %.3f, consecutive: %d/%d)", 
                    self.index, point_location, 
                    self.skip_probability * 100, random_value,
                    self.consecutive_skips, self.max_consecutive_skips)
        else:
            # Reset consecutive skips counter when we don't skip
            self.consecutive_skips = 0
            log.info("✅ Point Selection Randomization: Index %d - Point %s - EXECUTE (probability: %.1f%%, random: %.3f)", 
                    self.index, point_location, 
                    self.skip_probability * 100, random_value)
        
        return should_skip

    def detect_floors(self):
        """Detect Floor 1 and Floor 2 points based on Y coordinate and labels."""
        self.floor1_indices = []
        self.floor2_indices = []
        
        for i, component in enumerate(self.sequence):
            if isinstance(component, Point):
                y = component.location[1]
                point_added = False
                
                # Method 1: Label based (more robust - check previous component)
                if i > 0:
                    prev_component = self.sequence[i - 1]
                    if isinstance(prev_component, Label):
                        label_name = prev_component.label.lower()
                        if label_name.startswith('f1_'):
                            self.floor1_indices.append(i)
                            point_added = True
                        elif label_name.startswith('f2_'):
                            self.floor2_indices.append(i)
                            point_added = True
                
                # Method 2: Y coordinate based (fallback)
                if not point_added:
                    if y > 0.16:  # Floor 1 threshold
                        self.floor1_indices.append(i)
                    else:  # Floor 2 threshold
                        self.floor2_indices.append(i)
        
        log.info("🏢 Floor Detection: Floor 1: %d points, Floor 2: %d points", 
                 len(self.floor1_indices), len(self.floor2_indices))

    def get_f1_last_index(self):
        """Get index in self.sequence for f1_pos_last."""
        if not self.floor1_indices:
            return -1
        return self.floor1_indices[-1]
    
    def get_f1_first_index(self):
        """Get index in self.sequence for f1_pos_0."""
        if not self.floor1_indices:
            return -1
        return self.floor1_indices[0]
    
    def get_f2_last_index(self):
        """Get index in self.sequence for f2_pos_last."""
        if not self.floor2_indices:
            return -1
        return self.floor2_indices[-1]
    
    def get_f2_first_index(self):
        """Get index in self.sequence for f2_pos_0."""
        if not self.floor2_indices:
            return -1
        return self.floor2_indices[0]
    
    def get_current_floor_position(self, current_index):
        """Get current position index within floor (0-based) and floor type.
        
        Returns:
            tuple: (floor_type, position_index, sequence_index) or (None, -1, -1) if not in any floor
            floor_type: 'f1' or 'f2'
            position_index: 0-based index within floor (0 = pos_0, last = pos_last)
            sequence_index: index in self.sequence
        """
        if current_index in self.floor1_indices:
            position_index = self.floor1_indices.index(current_index)
            return ('f1', position_index, current_index)
        elif current_index in self.floor2_indices:
            position_index = self.floor2_indices.index(current_index)
            return ('f2', position_index, current_index)
        return (None, -1, -1)

    def _pick_switch_interval(self, variant=None):
        """Pick a switch interval based on variant type."""
        target_variant = variant if variant else self.current_variant
        if target_variant in ('floor1_only', 'floor2_only'):
            low, high = self.floor_variant_loop_range
            return random.randint(low, high)
        return random.randint(3, 7)

    def _build_variant_cycle(self):
        """Build the base variant cycle (normal only, reverse disabled for testing)."""
        base_cycle = ['normal']  # Disabled reverse for floor-only testing
        combined_cycle = []
        for variant in base_cycle:
            if variant not in combined_cycle:
                combined_cycle.append(variant)

        if not combined_cycle:
            combined_cycle = ['normal']

        self.variant_cycle = combined_cycle
        self.variant_cycle_index = 0
        self.current_variant = self.variant_cycle[0]
        self.variant_switch_interval = self._pick_switch_interval(self.current_variant)
        self.variant_switch_counter = 0
        self.floor_variant_active = False

        log.info("🔁 Routine Pattern Variation: Variant cycle set to %s", " -> ".join(self.variant_cycle))

    def _get_next_variant_in_cycle(self):
        """Advance to the next available variant in the cycle."""
        if not self.variant_cycle:
            self._build_variant_cycle()

        for _ in range(len(self.variant_cycle)):
            self.variant_cycle_index = (self.variant_cycle_index + 1) % len(self.variant_cycle)
            candidate = self.variant_cycle[self.variant_cycle_index]
            if candidate == 'floor1_only' and not self.floor1_indices:
                continue
            if candidate == 'floor2_only' and not self.floor2_indices:
                continue
            return candidate

        # Fallback if no other variant is available
        return 'normal'

    def _choose_floor_variant(self):
        """Choose which floor-only variant to activate (50% floor1, 50% floor2)."""
        options = []
        if self.floor1_indices:
            options.append('floor1_only')
        if self.floor2_indices:
            options.append('floor2_only')

        if not options:
            return None

        # If only one option available, use it
        if len(options) == 1:
            choice = options[0]
            self.floor_variant_last = choice
            return choice

        # 50% floor1_only, 50% floor2_only
        roll = random.random()
        if roll < 0.5:
            # 50% chance for floor1_only
            if 'floor1_only' in options:
                choice = 'floor1_only'
            else:
                choice = 'floor2_only'
        else:
            # 50% chance for floor2_only
            if 'floor2_only' in options:
                choice = 'floor2_only'
            else:
                choice = 'floor1_only'
        
        self.floor_variant_last = choice
        return choice

    def _switch_variant(self, forced_variant=None):
        """Switch to the next variant in the configured cycle or a forced variant."""
        if forced_variant:
            self.current_variant = forced_variant
            self.variant_switch_interval = self._pick_switch_interval(forced_variant)
            self.variant_switch_counter = 0
            self.floor_variant_active = forced_variant in ('floor1_only', 'floor2_only')
            log.info("🔄 Routine Pattern Variation: Switched to variant '%s' (switch every %d loops, %d loop(s) remaining before next switch)", 
                     self.current_variant, self.variant_switch_interval, self.variant_switch_interval)
            return

        # If floor-only was active, return to normal variant
        if self.floor_variant_active:
            self.floor_variant_active = False
            # Force switch to normal variant after floor-only completes
            self.current_variant = 'normal'
            # Reset to normal variant start index
            self.index = 0
            self.variant_switch_interval = random.randint(3, 7)  # Reset interval for normal variant
            self.variant_switch_counter = 0
            log.info("🔄 Routine Pattern Variation: Returned to normal variant from floor-only (switch every %d loops)", 
                     self.variant_switch_interval)
            return

        next_variant = self._get_next_variant_in_cycle()
        self.current_variant = next_variant

        # Reset switch counter and determine next interval
        self.variant_switch_interval = self._pick_switch_interval(self.current_variant)
        self.variant_switch_counter = 0

        log.info("🔄 Routine Pattern Variation: Switched to variant '%s' (switch every %d loops, %d loop(s) remaining before next switch)", 
                 self.current_variant, self.variant_switch_interval, self.variant_switch_interval)

    def _maybe_activate_floor_variant(self):
        """Randomly activate a floor-only variant after completing a loop."""
        if self.floor_variant_active or not self.variant_enabled:
            return False

        available = []
        if self.floor1_indices:
            available.append('floor1_only')
        if self.floor2_indices:
            available.append('floor2_only')

        if not available:
            return False

        roll = random.random()
        if roll >= self.floor_variant_chance:
            log.debug("Routine Pattern Variation: Floor-only chance skipped (chance: %.2f, roll: %.3f)", 
                      self.floor_variant_chance, roll)
            return False

        variant = self._choose_floor_variant()
        if not variant:
            return False

        self._switch_variant(forced_variant=variant)
        self.index = self._get_variant_start_index()
        self.last_index = -1
        self.last_floor_index = -1  # Reset last_floor_index when activating floor variant
        self.floor_variant_active = True
        
        # Log floor indices for debugging
        floor_indices = self.floor1_indices if variant == 'floor1_only' else self.floor2_indices
        log.info("🛗 Routine Pattern Variation: Activated floor-only variant '%s' for %d loop(s) (chance: %.0f%%, roll: %.3f)", 
                 variant, self.variant_switch_interval, self.floor_variant_chance * 100, roll)
        log.info("🛗 Floor-only: Floor indices: %s (total: %d points), Starting at index %d, Direction: %s", 
                 floor_indices, len(floor_indices), self.index, self.floor_direction)
        return True

    def _should_switch_variant(self):
        """Check if we should switch variant."""
        if not self.variant_enabled:
            return False
        
        # If floor-only variant is active, check if we've reached the loop limit
        if self.floor_variant_active and self.current_variant in ['floor1_only', 'floor2_only']:
            if self.variant_switch_counter >= self.variant_switch_interval:
                # Floor-only completed, return to normal
                log.info("🛗 Floor-only: Completed %d loop(s), returning to normal variant", self.variant_switch_interval)
                return True
        
        # Check if we've completed enough loops for normal variant switching
        # Note: variant_switch_counter is incremented in step() when loop completion is detected
        if self.variant_switch_counter >= self.variant_switch_interval:
            return True
        
        return False

    def _get_variant_start_index(self):
        """Get start index based on current variant."""
        if len(self.sequence) == 0:
            return 0
        
        if self.current_variant == 'normal':
            return 0
        elif self.current_variant == 'reverse':
            return len(self.sequence) - 1
        elif self.current_variant == 'floor1_only':
            # Floor1_only: Start from first position with forward direction (f1_pos_0 -> f1_pos_last)
            # When reaching f1_pos_last, will switch to reverse direction (f1_pos_last -> f1_pos_0)
            self.floor_direction = 'forward'  # Start in forward direction
            f1_first = self.get_f1_first_index()  # Get f1_pos_0 index in self.sequence
            return f1_first if f1_first >= 0 else 0
        elif self.current_variant == 'floor2_only':
            # Floor2_only: Start from last position and reverse direction (f2_pos_last -> f2_pos_1)
            self.floor_direction = 'reverse'  # Start in reverse direction
            f2_last = self.get_f2_last_index()  # Get f2_pos_last index in self.sequence
            return f2_last if f2_last >= 0 else 0
        return 0

    def _get_variant_next_index(self, current_index):
        """Get next index based on current variant."""
        if len(self.sequence) == 0:
            return 0
        
        if self.current_variant == 'normal':
            # Normal: forward
            return (current_index + 1) % len(self.sequence)
        elif self.current_variant == 'reverse':
            # Reverse: backward
            return (current_index - 1) % len(self.sequence)
        elif self.current_variant == 'floor1_only':
            # Floor 1 only: only visit Floor 1 points
            next_idx = self._get_next_floor_index(current_index, self.floor1_indices)
            log.debug("🛗 Floor1-only: Current index %d -> Next index %d (direction: %s)", 
                     current_index, next_idx, self.floor_direction)
            return next_idx
        elif self.current_variant == 'floor2_only':
            # Floor 2 only: only visit Floor 2 points
            next_idx = self._get_next_floor_index(current_index, self.floor2_indices)
            log.debug("🛗 Floor2-only: Current index %d -> Next index %d (direction: %s)", 
                     current_index, next_idx, self.floor_direction)
            return next_idx
        return (current_index + 1) % len(self.sequence)

    def _get_next_floor_index(self, current_index, floor_indices):
        """Get next index within a specific floor (forward: pos_0->pos_last, reverse: pos_last->pos_0)."""
        if not floor_indices:
            # Fallback to normal stepping if no floor indices
            return (current_index + 1) % len(self.sequence)
        
        # Determine floor type (f1 or f2) to use correct helper methods
        is_floor1 = floor_indices is self.floor1_indices
        is_floor2 = floor_indices is self.floor2_indices
        
        # Get first and last indices using helper methods to ensure sync with self.sequence
        if is_floor1:
            first_floor_idx = self.get_f1_first_index()  # f1_pos_0 index in self.sequence
            last_floor_idx = self.get_f1_last_index()    # f1_pos_last index in self.sequence
        elif is_floor2:
            first_floor_idx = self.get_f2_first_index()  # f2_pos_0 index in self.sequence
            last_floor_idx = self.get_f2_last_index()    # f2_pos_last index in self.sequence
        else:
            # Fallback: use direct access if floor_indices is not one of the known arrays
            first_floor_idx = floor_indices[0] if floor_indices else -1
            last_floor_idx = floor_indices[-1] if floor_indices else -1
        
        # Validate indices
        if first_floor_idx < 0 or last_floor_idx < 0:
            log.warning("🛗 Floor-only: Invalid floor indices (first=%d, last=%d), falling back to normal step", 
                       first_floor_idx, last_floor_idx)
            return (current_index + 1) % len(self.sequence)
        
        # Find current index in floor_indices
        try:
            current_floor_index = floor_indices.index(current_index)
            
            if self.floor_direction == 'forward':
                # Forward: move to next position
                if current_index == last_floor_idx:
                    # Reached last position, switch to reverse direction
                    # Move to last - 1 immediately (start reverse)
                    self.floor_direction = 'reverse'
                    if current_floor_index > 0:
                        next_floor_index = current_floor_index - 1
                        log.info("🛗 Floor-only: Reached last position %d, switching to REVERSE direction, moving to position %d", 
                                last_floor_idx, floor_indices[next_floor_index])
                        return floor_indices[next_floor_index]
                    else:
                        # Only one position, stay at last
                        log.info("🛗 Floor-only: Reached last position %d, switching to REVERSE direction", last_floor_idx)
                        return last_floor_idx
                else:
                    # Move forward to next position
                    next_floor_index = current_floor_index + 1
                    if next_floor_index < len(floor_indices):
                        next_idx = floor_indices[next_floor_index]
                        log.debug("🛗 Floor-only FORWARD: Moving from position %d (index %d) -> position %d (index %d)", 
                                 current_index, current_floor_index, next_idx, next_floor_index)
                        return next_idx
                    else:
                        # Should not happen, but fallback
                        return last_floor_idx
            else:  # reverse
                # Reverse: move to previous position
                if current_index == first_floor_idx:
                    # Reached first position, switch to forward direction
                    # Stay at first position, next step will go forward (loop completed)
                    self.floor_direction = 'forward'
                    log.info("🛗 Floor-only: Reached first position %d, switching to FORWARD direction (loop will complete on next step)", first_floor_idx)
                    return first_floor_idx
                else:
                    # Move reverse to previous position
                    next_floor_index = current_floor_index - 1
                    if next_floor_index >= 0:
                        next_idx = floor_indices[next_floor_index]
                        log.info("🛗 Floor-only REVERSE: Moving from position %d (index %d) -> position %d (index %d)", 
                                current_index, current_floor_index, next_idx, next_floor_index)
                        return next_idx
                    else:
                        # Should not happen, but fallback
                        log.warning("🛗 Floor-only REVERSE: Unexpected state at position %d, falling back to first", current_index)
                        return first_floor_idx
        except ValueError:
            # Current index not in floor, start from first floor point in forward direction
            self.floor_direction = 'forward'
            # Use helper methods to get correct first index
            if is_floor1:
                return self.get_f1_first_index() if self.get_f1_first_index() >= 0 else 0
            elif is_floor2:
                return self.get_f2_first_index() if self.get_f2_first_index() >= 0 else 0
            else:
                return floor_indices[0] if floor_indices else 0

    @utils.run_if_enabled
    def step(self):
        """Increments config.seq_index and wraps back to 0 at the end of config.sequence."""
        if len(self.sequence) == 0:
            return
        
        # Save current index before stepping
        old_index = self.index
        
        # Check if we should switch variant (before stepping)
        if self._should_switch_variant():
            self._switch_variant()
            # Reset to variant start index
            self.index = self._get_variant_start_index()
            self.last_index = -1  # Reset last_index after switching
            self.last_floor_index = -1  # Reset last_floor_index after switching
            log.info("🔄 Routine Pattern Variation: Reset to start index %d (variant: '%s')", 
                     self.index, self.current_variant)
            return
        
        # Step based on current variant
        old_idx_before_step = self.index
        self.index = self._get_variant_next_index(self.index)
        
        # Log step for floor-only variants
        if self.current_variant in ['floor1_only', 'floor2_only']:
            log.info("🛗 Floor-only STEP: Variant '%s', Index %d -> %d, Direction: %s", 
                    self.current_variant, old_idx_before_step, self.index, self.floor_direction)
        
        # Detect loop completion (after stepping)
        # A loop is completed when we've gone through ALL components in the routine according to the current variant
        loop_completed = False
        if self.last_index != -1:
            if self.current_variant == 'normal':
                # Normal: loop when index wraps from last to 0 (completed entire routine forward)
                if old_index == len(self.sequence) - 1 and self.index == 0:
                    loop_completed = True
            elif self.current_variant == 'reverse':
                # Reverse: loop when index wraps from 0 to last (completed entire routine backward)
                if old_index == 0 and self.index == len(self.sequence) - 1:
                    loop_completed = True
            elif self.current_variant in ['floor1_only', 'floor2_only']:
                # Floor-only: loop completed when we finish forward (pos_0->pos_last) then reverse (pos_last->pos_0)
                # A loop is complete when we return to first position after completing reverse direction
                floor_indices = self.floor1_indices if self.current_variant == 'floor1_only' else self.floor2_indices
                if floor_indices:
                    # Use helper methods to get correct first index in self.sequence
                    if self.current_variant == 'floor1_only':
                        first_floor_idx = self.get_f1_first_index()
                    else:  # floor2_only
                        first_floor_idx = self.get_f2_first_index()
                    
                    # Loop completed when: we're at first position, direction is forward (just switched from reverse),
                    # and we came from a position that's not first (completed reverse journey)
                    if (first_floor_idx >= 0 and 
                        self.index == first_floor_idx and 
                        self.floor_direction == 'forward' and 
                        old_index in floor_indices and 
                        old_index != first_floor_idx):
                        loop_completed = True
                        log.info("🛗 Floor-only: Loop completed! (forward: pos_0->pos_last, reverse: pos_last->pos_0)")
        
        # Only increment counters when a loop is actually completed
        if loop_completed:
            self.loop_count += 1
            self.variant_switch_counter += 1  # Increment counter for variant switching
            loops_remaining = self.variant_switch_interval - self.variant_switch_counter
            log.info("🔄 Routine Pattern Variation: Loop %d completed (variant: '%s', switch counter: %d/%d, %d loop(s) remaining before switch)", 
                     self.loop_count, self.current_variant, 
                     self.variant_switch_counter, self.variant_switch_interval,
                     loops_remaining)

            if not self.floor_variant_active:
                self._maybe_activate_floor_variant()
        
        # Update last_index for next iteration
        self.last_index = old_index
        
        # Update last_floor_index for floor-only variants (track last index within same floor)
        if self.current_variant in ['floor1_only', 'floor2_only']:
            floor_indices = self.floor1_indices if self.current_variant == 'floor1_only' else self.floor2_indices
            if floor_indices:
                # Only update if both old_index and current index are in the same floor
                if old_index in floor_indices and self.index in floor_indices:
                    self.last_floor_index = old_index
                else:
                    # Reset if switching between floors or entering/leaving floor
                    self.last_floor_index = -1
        else:
            # Reset when not in floor-only variant
            self.last_floor_index = -1
        
        # Log variant step (debug level)
        log.debug("Routine Pattern Variation: Variant '%s', Index: %d/%d", 
                  self.current_variant, self.index, len(self.sequence) - 1)

    def save(self, file_path):
        """Encodes and saves the current Routine at location PATH."""

        result = []
        for item in self.sequence:
            result.append(item.encode())
            if isinstance(item, Point):
                for c in item.commands:
                    result.append(' ' * 4 + c.encode())
        result.append('')

        with open(file_path, 'w') as file:
            file.write('\n'.join(result))
        self.dirty = False

        utils.print_separator()
        print(f"[~] Saved routine to '{basename(file_path)}'.")

    def clear(self):
        self.index = 0
        self.set([])
        self.dirty = False
        self.path = ''
        config.layout = None
        settings.reset()
        # Reset skip tracking
        self.consecutive_skips = 0
        self.is_skipping_context = False
        # Reset Routine Pattern Variation
        self.floor1_indices = []
        self.floor2_indices = []
        self.loop_count = 0
        self.last_index = -1
        self.variant_switch_counter = 0
        self.variant_cycle = []
        self.variant_cycle_index = 0
        self.floor_variant_active = False
        self.floor_variant_last = None
        self.floor_direction = 'forward'

        config.gui.clear_routine_info()

    def load(self, file=None):
        """
        Attempts to load FILE into a sequence of Components. If no file path is provided, attempts to
        load the previous routine file.
        :param file:    The file's path.
        :return:        None
        """

        utils.print_separator()
        print(f"[~] Loading routine '{basename(file)}':")

        if not file:
            if self.path:
                file = self.path
                print(' *  File path not provided, using previously loaded routine')
            else:
                print('[!] File path not provided, no routine was previously loaded either')
                return False

        ext = splitext(file)[1]
        if ext != '.csv':
            print(f" !  '{ext}' is not a supported file extension.")
            return False

        self.clear()

        # Compile and Link
        self.compile(file)
        for c in self.sequence:
            if isinstance(c, Jump):
                c.bind()

        self.dirty = False
        self.path = file
        config.layout = Layout.load(file)
        config.gui.view.status.set_routine(basename(file))
        config.gui.edit.minimap.draw_default()
        print(f" ~  Finished loading routine '{basename(splitext(file)[0])}'.")
        
        # Log routine info for Point Selection Randomization
        point_count = sum(1 for item in self.sequence if isinstance(item, Point))
        jump_count = sum(1 for item in self.sequence if isinstance(item, Jump))
        label_count = sum(1 for item in self.sequence if isinstance(item, Label))
        log.info("📊 Routine Loaded: %d Points, %d Jumps, %d Labels, %d Total Components", 
                point_count, jump_count, label_count, len(self.sequence))
        log.info("🎯 Point Selection Randomization: Ready (%.1f%% skip probability, max %d consecutive skips)", 
                self.skip_probability * 100, self.max_consecutive_skips)
        
        # Reload randomization settings when loading routine
        self._load_randomization_settings()
        
        # Initialize Routine Pattern Variation
        if self.variant_enabled:
            self.detect_floors()
            self._build_variant_cycle()
            self.index = self._get_variant_start_index()
            log.info("🔄 Routine Pattern Variation: Initialized with variant '%s' (switch every %d loops, %d loop(s) remaining before next switch)", 
                    self.current_variant, self.variant_switch_interval, self.variant_switch_interval)
            log.info("🛗 Routine Pattern Variation: Floor-only activation chance %.0f%%, loop range %d-%d", 
                     self.floor_variant_chance * 100, self.floor_variant_loop_range[0], self.floor_variant_loop_range[1])

    def compile(self, file):
        self.labels = {}
        with open(file, newline='') as f:
            csv_reader = csv.reader(f, skipinitialspace=True)
            curr_point = None
            line = 1
            for row in csv_reader:
                result = self._eval(row, line)
                if result:
                    if isinstance(result, Command):
                        if curr_point:
                            curr_point.commands.append(result)
                    else:
                        self.append_component(result)
                        if isinstance(result, Point):
                            curr_point = result
                line += 1

    def _eval(self, row, i):
        if row and isinstance(row, list):
            first, rest = row[0].lower(), row[1:]
            args, kwargs = utils.separate_args(rest)
            line_error = f' !  Line {i}: '

            if first in SYMBOLS:
                c = SYMBOLS[first]
            elif first in config.bot.command_book:
                c = config.bot.command_book[first]
            else:
                print(line_error + f"Command '{first}' does not exist.")
                return

            try:
                obj = c(*args, **kwargs)
                if isinstance(obj, Label):
                    obj.set_index(len(self))
                    self.labels[obj.label] = obj
                return obj
            except (ValueError, TypeError) as e:
                print(line_error + f"Found invalid arguments for '{c.__name__}':")
                print(f"{' ' * 4} -  {e}")

    @staticmethod
    def get_all_components():
        """Returns a dictionary mapping all creatable Components to their names."""

        options = config.bot.command_book.dict.copy()
        for e in (Point, Label, Jump, Setting):
            options[e.__name__.lower()] = e
        return options

    def __getitem__(self, i):
        return self.sequence[i]

    def __len__(self):
        return len(self.sequence)
